// CREDENTIALS LOGIN ACTIONS
export const LOGIN_START = 'LOGIN_START'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_U2F = 'LOGIN_U2F'
export const LOGIN_ERROR = 'LOGIN_ERROR'

// U2F LOGIN ACTIONS
export const U2F_REQUESTED = 'U2F_REQUESTED'
export const U2F_DEVICE_SUCCESS = 'U2F_DEVICE_SUCCESS'
export const U2F_DEVICE_ERROR = 'U2F_DEVICE_ERROR'
export const U2F_SEND_CHALLENGE = 'U2F_SEND_CHALLENGE'
export const U2F_SERVER_SUCCESS = 'U2F_SERVER_SUCCESS'
export const U2F_SERVER_ERROR = 'U2F_SERVER_ERROR'

// U2F DEVICE MANAGEMENT ACTIONS
export const ADD_U2F_DEVICE = 'ADD_U2F_DEVICE'
export const U2F_DEVICE_CHALLENGE = 'U2F_DEVICE_CHALLENGE'
export const U2F_DEVICE_CHALLENGE_SUCCESS = 'U2F_DEVICE_CHALLENGE_SUCCESS'
export const U2F_DEVICE_CHALLENGE_ERROR = 'U2F_DEVICE_CHALLENGE_ERROR'
export const U2F_DEVICE_REGISTER = 'U2F_DEVICE_REGISTER'
export const U2F_DEVICE_REGISTER_SUCCESS = 'U2F_DEVICE_REGISTER_SUCCESS'
export const U2F_DEVICE_REGISTER_ERROR = 'U2F_DEVICE_REGISTER_ERROR'
