// CREDENTIALS LOGIN ACTIONS
export const LOGIN_START = 'LOGIN_START'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_PENDING = 'LOGIN_PENDING' // WHEN U2F IS REQUESTED
export const LOGIN_ERROR = 'LOGIN_ERROR'

// U2F LOGIN ACTIONS
export const U2F_REQUESTED = 'U2F_REQUESTED' // SIDE EFFECT OF LOGIN_SUCCESS
export const U2F_DEVICE_SUCCESS = 'U2F_DEVICE_SUCCESS'
export const U2F_DEVICE_ERROR = 'U2F_DEVICE_ERROR'
export const U2F_SEND = 'U2F_SEND'
export const U2F_SUCCESS = 'U2F_SUCCESS'
export const U2F_ERROR = 'U2F_ERROR'

// U2F DEVICE MANAGEMENT ACTIONS
export const ADD_U2F_DEVICE = 'ADD_U2F_DEVICE'
export const U2F_DEVICE_CHALLENGE = 'U2F_DEVICE_CHALLENGE'
export const U2F_DEVICE_CHALLENGE_SUCCESS = 'U2F_DEVICE_CHALLENGE_SUCCESS'
export const U2F_DEVICE_CHALLENGE_ERROR = 'U2F_DEVICE_CHALLENGE_ERROR'
export const U2F_DEVICE_REGISTER = 'U2F_DEVICE_REGISTER'
export const U2F_DEVICE_REGISTER_SUCCESS = 'U2F_DEVICE_REGISTER_SUCCESS'
export const U2F_DEVICE_REGISTER_ERROR = 'U2F_DEVICE_REGISTER_ERROR'
